export const CLEAR = 'calculator/CLEAR'
export const ENTER_NUMBER = 'calculator/ENTER_NUMBER'
export const EVALUATE = 'calculator/EVALUATE'
export const PERCENTAGE = 'calculator/PERCENTAGE'
export const SET_OPERATOR = 'calculator/SET_OPERATOR'
export const TOGGLE_NEGATIVE = 'calculator/TOGGLE_NEGATIVE'
